commit

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -1,27 +1,20 @@
 name: Deploy static content to Pages
 
 on:
-  # Runs on pushes targeting the default branch
   push:
     branches: ["main"]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
   contents: read
   pages: write
   id-token: write
 
-# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
-# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
   group: "pages"
   cancel-in-progress: false
 
 jobs:
-  # Single deploy job since we're just deploying
   deploy:
     environment:
       name: github-pages
@@ -34,16 +27,25 @@ jobs:
       - name: Debug working directory
         run: ls -R # List all files in the repository
 
+      - name: Verify package.json exists
+        run: |
+          if [ -f "package.json" ]; then
+            echo "package.json found!"
+          else
+            echo "package.json not found!"
+            exit 1
+          fi
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: 18 # Use the Node.js version required by your project
+          node-version: 18
 
       - name: Install dependencies
         run: npm install
 
       - name: Build static content
-        run: npm run build # This runs "webpack" and generates the /dist folder
+        run: npm run build
 
       - name: Setup Pages
         uses: actions/configure-pages@v5
@@ -51,7 +53,6 @@ jobs:
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          # Upload only the /dist folder
           path: 'dist'
 
       - name: Deploy to GitHub Pages
